// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmlkapxvilsvnkroerqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tbGthcHh2aWxzdm5rcm9lcnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzA0NzMsImV4cCI6MjA2NTMwNjQ3M30.Xt5M5t0r4NegMwEgqaWkvhPlIFsBj-0YfIsQdSTY9IA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);